export const blockedIpsData = [
  {
    id: 1,
    ip: "192.168.1.10",
    country: "Nepal",
    reason: "SQL Injection",
    severity: "Critical",
    status: "Active",
    blockedAt: "2 mins ago",
  },
  {
    id: 2,
    ip: "172.16.5.23",
    country: "India",
    reason: "Brute Force",
    severity: "High",
    status: "Active",
    blockedAt: "5 mins ago",
  },
  {
    id: 3,
    ip: "10.10.0.8",
    country: "USA",
    reason: "Malware",
    severity: "Medium",
    status: "Active",
    blockedAt: "12 mins ago",
  },
  {
    id: 4,
    ip: "185.25.11.45",
    country: "China",
    reason: "Port Scanning",
    severity: "Low",
    status: "Released",
    blockedAt: "25 mins ago",
  },
  {
    id: 5,
    ip: "45.88.20.91",
    country: "Russia",
    reason: "DDoS Attempt",
    severity: "Critical",
    status: "Active",
    blockedAt: "35 mins ago",
  },
  {
    id: 6,
    ip: "203.12.100.44",
    country: "Japan",
    reason: "Credential Stuffing",
    severity: "High",
    status: "Released",
    blockedAt: "1 hour ago",
  },
  {
    id: 7,
    ip: "91.188.77.65",
    country: "Germany",
    reason: "XSS Attack",
    severity: "Medium",
    status: "Active",
    blockedAt: "2 hours ago",
  },
  {
    id: 8,
    ip: "61.19.77.8",
    country: "Singapore",
    reason: "Bot Activity",
    severity: "Low",
    status: "Active",
    blockedAt: "3 hours ago",
  },
];